# Default values for file-distribution-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  labels:
    app.kubernetes.io/part-of: fdo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: fdo
  namespace: filedistribution
  secretName: files
  fileName: sample.txt
  destination: /test/test3/sample11.txt
  filepermissions: "644"
  rescheduleInterval: 1

secret:
  sampletxt: SGVsbG8gd29ybGQhCg==
