# permissions for end users to view filedistributionconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: filedistributionconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fdo
    app.kubernetes.io/part-of: fdo
    app.kubernetes.io/managed-by: kustomize
  name: filedistributionconfig-viewer-role
rules:
- apiGroups:
  - krenn.dev
  resources:
  - filedistributionconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - krenn.dev
  resources:
  - filedistributionconfigs/status
  verbs:
  - get
