---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - krenn.dev
  resources:
  - filedistributionconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - krenn.dev
  resources:
  - filedistributionconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - krenn.dev
  resources:
  - filedistributionconfigs/status
  verbs:
  - get
  - patch
  - update
