apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: {{ .Values.config.prefix }}controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: {{ .Values.config.prefix }}system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: fdo
    app.kubernetes.io/part-of: fdo
    app.kubernetes.io/managed-by: kustomize
  name: {{ .Values.config.namespace }}