apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: {{ .Values.config.prefix }}controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: {{ .Values.config.prefix }}controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: fdo
    app.kubernetes.io/part-of: fdo
    app.kubernetes.io/managed-by: kustomize
  name: {{ .Values.config.prefix }}controller-manager
  namespace: {{ .Values.config.namespace }}
spec:
  selector:
    matchLabels:
      control-plane: {{ .Values.config.prefix }}controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: {{ .Values.config.prefix }}controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - command:
            - /manager
          args:
            - --leader-elect
          image: {{ .Values.config.image }}
          name: manager
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: {{ .Values.config.prefix }}controller-manager
      terminationGracePeriodSeconds: 10
