apiVersion: krenn.dev/v1alpha1
kind: FileDistributionConfig
metadata:
  labels:
    app.kubernetes.io/name: filedistributionconfig
    app.kubernetes.io/instance: filedistributionconfig-sample
    app.kubernetes.io/part-of: fdo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: fdo
  name: filedistributionconfig-sample
  namespace: fdo-system
spec:
  secretName: files
  fileName: sample.txt
  # destination: specify a directory by adding / at the end otherwise it will be treaded as file
  destination: /tmp/sample3.txt
  # filepermissions: will default to 644
  filepermissions: "644"
  # interval given in minutes, default 10
  rescheduleInterval: 10

---

apiVersion: v1
kind: Secret
metadata:
  name: files
  namespace: fdo-system
data:
  sample.txt: U29tZXRoaW5nCg==
  sample2.txt: b3RoZXJ3aXMK