apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: {{ .Values.config.prefix }}leader-election-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fdo
    app.kubernetes.io/part-of: fdo
    app.kubernetes.io/managed-by: kustomize
  name: {{ .Values.config.prefix }}leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.config.prefix }}leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.config.prefix }}controller-manager
  namespace: {{ .Values.config.namespace }}
