apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: {{ .Values.config.prefix }}controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fdo
    app.kubernetes.io/part-of: fdo
    app.kubernetes.io/managed-by: kustomize
  name: {{ .Values.config.prefix }}controller-manager
  namespace: {{ .Values.config.namespace }}
